import React, { useState } from 'react';
import { Compass, CheckCircle, BookOpen, Clock, Code, Award, Check } from 'lucide-react';

interface SubNode {
  name: string;
  duration: string;
  concepts: string[];
  materials: string;
  completed: boolean;
}

interface RoadmapStage {
  title: string;
  description: string;
  subNodes: SubNode[];
}

const LearningRoadmap: React.FC = () => {
  const [stages, setStages] = useState<RoadmapStage[]>([
    {
      title: 'Stage 1: Advanced Frontend Engineering',
      description: 'Master component efficiency, state synchronization, and reactive styling.',
      subNodes: [
        { name: 'React Architecture', duration: '5 hours', concepts: ['Fiber reconciler', 'Custom hooks optimization', 'Concurrent rendering'], materials: 'Read React Dev Guides, build mock custom hook libraries.', completed: true },
        { name: 'TypeScript Core', duration: '3 hours', concepts: ['Generic typings', 'Discriminated unions', 'Utility definitions'], materials: 'TS playground tasks, strict typing configurations.', completed: true },
        { name: 'Bundling & Performance', duration: '4 hours', concepts: ['Vite config optimization', 'Dynamic lazy loading', 'Memory leak audits'], materials: 'Optimize large bundle sizes, implement image responsive tags.', completed: false },
      ],
    },
    {
      title: 'Stage 2: Robust Backend Systems',
      description: 'Design RESTful specifications, relational storage structures, and middleware.',
      subNodes: [
        { name: 'Node.js Event Loop', duration: '4 hours', concepts: ['Microtasks and Macrotasks', 'Cluster scaling', 'Event Emitters'], materials: 'Write multi-thread worker nodes, handle intensive processing.', completed: false },
        { name: 'Relational Database Schema', duration: '5 hours', concepts: ['Index optimization', 'Transactions isolation', 'Join configurations'], materials: 'Write Postgres indexing plans, debug connection pool sizes.', completed: false },
      ],
    },
    {
      title: 'Stage 3: Algorithms & Interview Prep',
      description: 'Core logic patterns for algorithmic interview coding test clearance.',
      subNodes: [
        { name: 'Graph Theory', duration: '8 hours', concepts: ['DFS & BFS implementations', 'Dijkstra shortest path', 'Union Find structure'], materials: 'Solve LeetCode Graph tags, build visual routing path grids.', completed: false },
        { name: 'Dynamic Programming', duration: '10 hours', concepts: ['Memoization strategies', 'Tabulation methods', 'Knapsack patterns'], materials: 'Code subset sum solutions, benchmark recursive speed differences.', completed: false },
      ],
    },
  ]);

  const [activeNode, setActiveNode] = useState<SubNode | null>(stages[0].subNodes[2]);

  // Calculate completion percentage
  const totalNodes = stages.reduce((acc, st) => acc + st.subNodes.length, 0);
  const completedNodes = stages.reduce((acc, st) => acc + st.subNodes.filter((n) => n.completed).length, 0);
  const progressPercent = Math.round((completedNodes / totalNodes) * 100);

  const toggleNodeCompletion = (sIdx: number, nIdx: number) => {
    const updatedStages = [...stages];
    const node = updatedStages[sIdx].subNodes[nIdx];
    node.completed = !node.completed;
    setStages(updatedStages);
    // Sync current active node details
    if (activeNode && activeNode.name === node.name) {
      setActiveNode({ ...node });
    }
  };

  return (
    <div className="space-y-6 fade-slide-up">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            <Compass className="h-6 w-6 text-indigo-400" /> AI Career Learning Roadmap
          </h1>
          <p className="text-slate-400 text-xs mt-1">
            Custom learning paths generated by AI based on your resume skill gaps and targeted role objectives.
          </p>
        </div>

        {/* Overall progress card */}
        <div className="rounded-2xl border border-slate-900 bg-slate-900/30 p-4 shrink-0 flex items-center gap-4 shadow-md w-full sm:w-auto">
          <div className="text-left">
            <p className="text-[10px] text-slate-550 font-bold uppercase">Learning Progress</p>
            <p className="text-base font-extrabold text-white">{progressPercent}% Completed</p>
          </div>
          <div className="w-24 bg-slate-950 border border-slate-900 rounded-full h-2 overflow-hidden shrink-0">
            <div className="bg-indigo-500 h-full rounded-full transition-all duration-300" style={{ width: `${progressPercent}%` }} />
          </div>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-5">
        {/* Left Side: Timeline Stages flow */}
        <div className="lg:col-span-3 space-y-6 max-h-[600px] overflow-y-auto pr-1 scrollbar-thin">
          {stages.map((stage, sIdx) => (
            <div key={sIdx} className="rounded-3xl border border-slate-900 bg-slate-900/20 p-5 space-y-4">
              <div>
                <h3 className="text-sm font-bold text-slate-200">{stage.title}</h3>
                <p className="text-[10px] text-slate-500 mt-0.5">{stage.description}</p>
              </div>

              <div className="space-y-3">
                {stage.subNodes.map((node, nIdx) => {
                  const isNodeActive = activeNode?.name === node.name;
                  return (
                    <div
                      key={node.name}
                      onClick={() => setActiveNode(node)}
                      className={`rounded-2xl p-4 border transition-all flex items-center justify-between cursor-pointer ${
                        isNodeActive
                          ? 'bg-indigo-950/60 border-indigo-900 text-indigo-250 shadow-inner'
                          : 'bg-slate-950/30 border-slate-950 text-slate-400 hover:border-slate-800'
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            toggleNodeCompletion(sIdx, nIdx);
                          }}
                          className={`h-5 w-5 rounded-md border flex items-center justify-center transition-all ${
                            node.completed
                              ? 'bg-emerald-500 border-emerald-400 text-white'
                              : 'border-slate-800 hover:border-slate-600 bg-slate-900'
                          }`}
                        >
                          {node.completed && <Check className="h-3.5 w-3.5" />}
                        </button>

                        <div>
                          <p className="text-xs font-bold text-slate-200">{node.name}</p>
                          <span className="text-[9px] text-slate-550 flex items-center gap-1 mt-0.5">
                            <Clock className="h-3 w-3" /> {node.duration}
                          </span>
                        </div>
                      </div>

                      <BookOpen className={`h-4 w-4 shrink-0 ${isNodeActive ? 'text-indigo-400 animate-pulse' : 'text-slate-650'}`} />
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {/* Right Side: Topic Content Viewer */}
        <div className="lg:col-span-2 space-y-6">
          {activeNode ? (
            <div className="rounded-3xl border border-slate-900 bg-slate-900/30 p-6 space-y-5 h-fit sticky top-20 fade-in">
              <div>
                <span className="text-[9px] font-black uppercase text-indigo-455 tracking-wider bg-indigo-950/40 border border-indigo-900 px-3 py-1 rounded-full">
                  Topic Academy Details
                </span>
                <h2 className="text-base font-extrabold text-slate-100 mt-3">{activeNode.name}</h2>
                <p className="text-[10px] text-slate-500 mt-0.5">Learn concepts and practice tasks to mark complete</p>
              </div>

              <div className="space-y-4 font-sans">
                <div className="space-y-2">
                  <span className="text-[10px] font-black uppercase tracking-wider text-slate-500 block">Syllabus Concepts</span>
                  <div className="flex flex-wrap gap-1.5">
                    {activeNode.concepts.map((c) => (
                      <span key={c} className="rounded-lg bg-slate-950/60 border border-slate-900 px-2.5 py-1 text-xs text-slate-350">
                        {c}
                      </span>
                    ))}
                  </div>
                </div>

                <div className="rounded-2xl bg-slate-950/60 border border-slate-900 p-4 space-y-2">
                  <span className="text-[10px] font-bold text-indigo-400 block uppercase">Recommended Activity</span>
                  <p className="text-xs text-slate-400 leading-relaxed font-sans">{activeNode.materials}</p>
                </div>
              </div>

              <div className="pt-4 border-t border-slate-900 flex justify-between items-center">
                <span className="text-xs text-slate-500 font-medium">Estimated time: {activeNode.duration}</span>
                <button
                  onClick={() => {
                    // Toggle in state
                    let found = false;
                    const updatedStages = stages.map((st, sIdx) => {
                      const nIdx = st.subNodes.findIndex((n) => n.name === activeNode.name);
                      if (nIdx !== -1) {
                        found = true;
                        const copy = [...stages];
                        copy[sIdx].subNodes[nIdx].completed = !copy[sIdx].subNodes[nIdx].completed;
                        return copy;
                      }
                      return null;
                    });
                    if (found) {
                      const updated = [...stages];
                      setStages(updated);
                      setActiveNode({ ...activeNode, completed: !activeNode.completed });
                    }
                  }}
                  className={`rounded-xl px-4 py-2.5 text-xs font-bold transition-all ${
                    activeNode.completed
                      ? 'bg-slate-950 border border-slate-900 text-slate-400 hover:text-white'
                      : 'bg-indigo-650 text-white hover:bg-indigo-600'
                  }`}
                >
                  {activeNode.completed ? 'Mark Incomplete' : 'Complete Topic'}
                </button>
              </div>
            </div>
          ) : (
            <div className="rounded-3xl border border-dashed border-slate-800 p-8 text-center text-slate-500">
              <Compass className="mx-auto h-8 w-8 text-slate-655 mb-2" />
              <p className="text-sm font-semibold">Select a topic node</p>
              <p className="text-xs mt-1 text-slate-655">Select nodes in the timeline flowchart to view details.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default LearningRoadmap;
